# vim: ts=2 sw=2 et :
---
language: python

sudo: required

services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - molecule test --scenario-name default
  - molecule test --scenario-name netinstall

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
