---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true

- name: install packages
  become: yes
  package:
    name: "{{ item }}"
    state: "{{ ubuntu_installer_package_state }}"
  with_items: "{{ ubuntu_installer_package_names }}"

- name: create temporary target directory
  tempfile:
    state: directory
    prefix: iso
  register: tmpdir_dest
  changed_when: false

- name: create image target directory
  file:
    state: directory
    path: "{{ ubuntu_installer_target_dir }}"

- name: register source ubuntu iso file
  set_fact:
    src_iso: "{{ ubuntu_installer_target_dir }}/ubuntu.{{ ubuntu_installer_release }}.iso"

- name: fetch ubuntu source iso
  get_url:
    url: "http://releases.ubuntu.com/{{ ubuntu_installer_release }}/ubuntu-{{ ubuntu_installer_release }}-server-amd64.iso"
    dest: "{{ src_iso }}"

- name: extract ubuntu source iso
  command: "7z x {{ src_iso }}"
  args:
    chdir: "{{ tmpdir_dest.path }}"
  changed_when: false
  become: yes

- name: define installation menu language
  copy:
    dest: "{{ tmpdir_dest.path }}/isolinux/lang"
    content: en
  become: yes
  changed_when: false

- name: configure isolinux
  lineinfile:
    path: "{{ tmpdir_dest.path }}/isolinux/isolinux.cfg"
    regexp: 'timeout\s+[0-9]+'
    line: 'timeout 1'
  become: yes
  changed_when: false

- name: register seed file
  set_fact:
    seed_file: "ubuntu.seed"

- name: create seed file
  template:
    src: ubuntu.seed.j2
    dest: "{{ tmpdir_dest.path }}/{{ seed_file }}"
  vars:
    hostname: "{{ ubuntu_installer_hostname | split_with('.') | head }}"
    domain: "{{ ubuntu_installer_hostname | split_with('.') | tail | join('.') }}"
    timezone: "{{ ubuntu_installer_timezone }}"
    username: "{{ ubuntu_installer_username }}"
    password: "{{ ubuntu_installer_password }}"
    sshkey: "{{ ubuntu_installer_sshkey }}"
    late_command: "{{ ubuntu_installer_late_command | default('') }}"
    interface: "{{ ubuntu_installer_interface }}"
    disk: "{{ ubuntu_installer_disk | default('') }}"
    halt: "{{ ubuntu_installer_halt | default('false') }}"
  become: yes
  changed_when: false

- name: retrieve seed file checksum
  command: "md5sum {{ tmpdir_dest.path }}/{{ seed_file }}"
  register: seed_md5sum
  changed_when: false

- name: set bootloader preseed configuration
  template:
    src: isolinux.txt.j2
    dest: "{{ tmpdir_dest.path }}/isolinux/txt.cfg"
  vars:
    preseed_file: "{{ seed_file }}"
    preseed_checksum: "{{ seed_md5sum.stdout | split_with(' ') | first }}"
  become: yes
  changed_when: false

- name: create ubuntu autoinstall iso
  command: "mkisofs -D -r -V '{{ ubuntu_installer_hostname }}' -cache-inodes -J -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o {{ ubuntu_installer_target_dir }}/{{ ubuntu_installer_hostname }}.iso ."
  args:
    chdir: "{{ tmpdir_dest.path }}"
  become: yes
  changed_when: false

- name: make iso bootable
  command: "isohybrid {{ ubuntu_installer_target_dir }}/{{ ubuntu_installer_hostname }}.iso"
  become: yes
  changed_when: false

- name: remove temporary directories
  file:
    path: "{{ tmpdir_dest.path }}"
    state: absent
  become: yes
  changed_when: false
