---
- name: install packages
  package:
    name: "{{ ubuntu_installer_packages }}"
    state: "{{ ubuntu_installer_package_state }}"

- name: create temporary target directory
  tempfile:
    state: directory
    prefix: iso
  register: tmpdir_dest

- name: create image target directory
  file:
    state: directory
    path: "{{ ubuntu_installer_target_dir }}"

- name: fetch ubuntu source iso
  get_url:
    url: "{{ ubuntu_installer_image_url }}"
    dest: "{{ ubuntu_installer_iso_path }}"

- name: create temporary mount fstab
  tempfile:
    state: directory
    prefix: fstab
  register: mntfile_dest

- name: create temporary mount directory
  tempfile:
    state: directory
    prefix: mnt
  register: mntdir_dest

- name: mount ubuntu source iso
  mount:
    src: "{{ ubuntu_installer_iso_path }}"
    path: "{{ mntdir_dest.path }}"
    state: mounted
    opts: loop
    fstype: iso9660

- name: extract source iso files
  command: "cp -a {{ mntdir_dest.path }}/. {{ tmpdir_dest.path }}/"
  args:
    warn: no
  tags:
    - skip_ansible_lint

- name: unmount ubuntu source iso
  mount:
    src: "{{ ubuntu_installer_iso_path }}"
    path: "{{ mntdir_dest.path }}"
    state: absent
    opts: loop

- name: remove temporary mount directory
  file:
    path: "{{ mntdir_dest.path }}"
    state: absent

- name: remove temporary mount fstab
  file:
    path: "{{ mntfile_dest.path }}"
    state: absent

- include_tasks: live.yml

- name: remove temporary directories
  file:
    path: "{{ tmpdir_dest.path }}"
    state: absent
