---
- name: prepare cache

  hosts: localhost

  connection: local

  gather_facts: no

  vars_files:
    - vars.yml

  tasks:

    - name: create molecule cache dir
      file:
        path: "{{ cache_dir }}"
        state: directory

    - name: create kvm key pair
      command: "ssh-keygen -t rsa -f {{ kvm_key_pair_path }} -q -P ''"
      when: not kvm_key_pair_local.stat.exists
