---
bridge_net: '192.168.255.0/24'
__bridge_net: "{{ bridge_net | ipv4('network/prefix') }}"
bridge_host: "{{ __bridge_net | nthhost(1) }}"
bridge_prefix: "{{ __bridge_net | ipaddr('prefix') }}"
bridge_name: dummybr0
iface_name: dummy0
cache_dir: /tmp/molecule
ssh_keypair: "{{ cache_dir }}/id_rsa"
ubuntu_installers:
  focal:
    dest: "file://{{ cache_dir }}/focal-live.iso"
    url: "{{ focal_url | default('https://releases.ubuntu.com/20.04.1/ubuntu-20.04.1-live-server-amd64.iso') }}"
  groovy:
    dest: "file://{{ cache_dir }}/groovy-live.iso"
    url: "{{ groovy_url | default('https://releases.ubuntu.com/20.10/ubuntu-20.10-live-server-amd64.iso') }}"
vms:
  - ubuntu_installer_hostname: focal-lvm
    ubuntu_installer_ref: focal
    ubuntu_installer_interface:
      static: true
      ipaddress: "{{ __bridge_net | nthhost(2) }}"
      network: "{{ __bridge_net | ipaddr('network') }}"
      netmask: "{{ __bridge_net | ipaddr('netmask') }}"
      gateway: "{{ bridge_host }}"
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
    ubuntu_installer_partman_method: lvm
  - ubuntu_installer_hostname: focal-static
    ubuntu_installer_ref: focal
    ubuntu_installer_interface:
      static: true
      ipaddress: "{{ __bridge_net | nthhost(3) }}"
      network: "{{ __bridge_net | ipaddr('network') }}"
      netmask: "{{ __bridge_net | ipaddr('netmask') }}"
      gateway: "{{ bridge_host }}"
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
    ubuntu_installer_partman_method: regular
