---
- name: Verify iso creation

  hosts: all

  gather_facts: false

  vars_files:
    - ./vars.yml

  tasks:

    - name: retrieve iso status
      stat:
        path: "{{ cache_dir }}/{{ vm.ubuntu_installer_hostname }}.iso"
      vars:
        ubuntu_installer_target_dir: "{{ playbook_dir }}"
      loop_control:
        loop_var: vm
        label: "{{ vm.ubuntu_installer_hostname }}"
      loop: "{{ vms }}"
      register: vm_isos

    - name: verify iso creation
      assert:
        that:
          - vm_iso.stat.exists | bool
      loop_control:
        loop_var: vm_iso
        label: "{{ vm_iso.stat.path | default('unknown') }}"
      loop: "{{ vm_isos.results }}"


- name: Add vms to inventory

  hosts: all

  become: yes

  vars_files:
    - ./vars.yml

  tasks:

    - block:

        - name: add vm to inventory
          add_host:
            name: "{{ vm_hostname }}"
            groups:
              - install
            ansible_host: "{{ vm_address }}"
            ansible_user: 'molecule'
            ansible_ssh_private_key_file: "{{ ssh_keypair | regex_replace('.pub$', '') }}"
            ansible_ssh_common_args: "{{ ssh_args | default(omit) }}"
            partman_method: "{{ vm.ubuntu_installer_partman_method }}"
          vars:
            vm_hostname: "{{ vm.ubuntu_installer_hostname }}"
            vm_address: "{{ vm.ubuntu_installer_interface.ipaddress }}"
          loop_control:
            loop_var: vm
            label: "{{ vm.ubuntu_installer_hostname }}"
          loop: "{{ vms }}"

      when: kvm_enabled | bool


- name: Test vms

  hosts: install

  gather_facts: no

  tasks:

    - name: test connection
      wait_for_connection:
        delay: 300
        sleep: 10
        timeout: 900

    - name: gather partition info
      shell: "lsblk -l | grep /$"
      register: lsblk_output

    - name: check static partitioning
      fail:
        msg: "regular partitioning failed: {{ lsblk_output.stdout }}"
      when:
        - lsblk_output.stdout is not search('part')
        - partman_method == 'regular'

    - name: check lvm partitioning
      fail:
        msg: "lvm partitioning failed: {{ lsblk_output.stdout }}"
      when:
        - lsblk_output.stdout is not search('lvm')
        - partman_method == 'lvm'
