---
- name: Prepare

  hosts: all

  become: yes

  vars_files:
    - ../vars.yml

  tasks:

    - name: destroy vm
      virt:
        command: destroy
        name: "{{ vm.ubuntu_installer_hostname }}"
      loop_control:
        loop_var: vm
        label: "{{ vm.ubuntu_installer_hostname }}"
      loop: "{{ vms }}"
      failed_when: false

    - name: undefine vm
      virt:
        command: undefine
        name: "{{ vm.ubuntu_installer_hostname }}"
      loop_control:
        loop_var: vm
        label: "{{ vm.ubuntu_installer_hostname }}"
      loop: "{{ vms }}"
      failed_when: false

    - name: destroy disks
      file:
        path: "{{ vm_disk }}"
        state: absent
      vars:
        vm_disk: "{{ playbook_dir }}/{{ vm.ubuntu_installer_hostname }}.img"
      loop_control:
        loop_var: vm
        label: "{{ vm.ubuntu_installer_hostname }}"
      loop: "{{ vms }}"

    - name: detroy dummy bridge slave
      command: "nmcli con del {{ bridge_name }}-{{ iface_name }}"
      failed_when: false

    - name: destroy dummy bridge
      command: "nmcli con del {{ bridge_name }}"
      failed_when: false
