---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: ubuntu
    image: ubuntu:xenial
provisioner:
  name: ansible
scenario:
  name: default
  test_sequence:
    - dependency
    - syntax
verifier:
  name: testinfra
