---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu
    image: ubuntu:xenial
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - dependency
    - syntax
    - lint
verifier:
  name: testinfra
  lint:
    name: flake8
