---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: instance
    image: ami-06866e21db8917d18
    instance_type: a1.metal
provisioner:
  name: ansible
  playbooks:
    converge: ../converge.yml
    verify: ../verify.yml
    prepare: ../prepare.yml
    cleanup: ../cleanup.yml
  inventory:
    group_vars:
      all:
        kvm_enabled: ${MOLECULE_TEST_KVM:-true}
        aws_region: us-east-1
        aws_subnet_id: subnet-d2a31c8b
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
